Repository oguuk/ios-wanted-VoiceRecorder, pull requests merged in 2022-06, with the labels that each got.

#3 [#1] 프로젝트 초기 세팅
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  VoiceRecorder.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  VoiceRecorder/Application/AppDelegate.swift
  VoiceRecorder/Application/SceneDelegate.swift
  VoiceRecorder/Info.plist
  VoiceRecorder/Presentation/Home/HomeView.swift
  VoiceRecorder/Presentation/Home/HomeViewController.swift
  VoiceRecorder/Presentation/Play/PlayView.swift
  VoiceRecorder/Presentation/Play/PlayViewController.swift
  VoiceRecorder/Presentation/Recording/RecordingView.swift
  VoiceRecorder/Presentation/Recording/RecordingViewController.swift
  VoiceRecorder/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  VoiceRecorder/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  VoiceRecorder/Resource/Assets.xcassets/Contents.json
  VoiceRecorder/Resource/Base.lproj/LaunchScreen.storyboard
  VoiceRecorder/Util/Base/BaseViewController.swift
  VoiceRecorder/Util/Protocol/ViewPresentable.swift
Labels: Setting, 승찬

#5 [#4] Model 타입 생성
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder/Domain/Entity/AudioInformation.swift
Labels: Add, 날라

#6 [#2] Branch 생성
  VoiceRecorder.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Add, 국

#8 [#7] Firebase Storage 구현
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  VoiceRecorder/Domain/Entity/AudioURL.swift
  VoiceRecorder/Domain/Inteface/FirebaseRepositoryInterface.swift
  VoiceRecorder/Domain/Inteface/Repository/FirebaseRepository.swift
  VoiceRecorder/Domain/UseCase/FirebaseUseCase.swift
Labels: Feat, 승찬

#12 [#11] Data layer의 FirebaseRepository 구현
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  VoiceRecorder/Application/AppDelegate.swift
  VoiceRecorder/Application/SceneDelegate.swift
  VoiceRecorder/Data/Repository/FirebaseRepository.swift
  VoiceRecorder/Domain/Inteface/Repository/FirebaseRepositoryInterface.swift
  VoiceRecorder/Domain/UseCase/FirebaseUseCase.swift
Labels: Feat, 날라
