Repository oguuk/ios-wanted-VoiceRecorder, pull requests merged in 2022-07, with the labels that each got.

#15 [#13] FirebaseRepository 리팩토링
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder/Application/SceneDelegate.swift
  VoiceRecorder/Data/Repository/FirebaseRepository.swift
  VoiceRecorder/Domain/Entity/AudioURL.swift
  VoiceRecorder/Domain/Inteface/Repository/AudioRepository.swift
  VoiceRecorder/Domain/Inteface/Repository/FirebaseRepositoryInterface.swift
  VoiceRecorder/Domain/UseCase/FirebaseUseCase.swift
  VoiceRecorder/GoogleService-Info.plist
  VoiceRecorder/Presentation/AudioList/AudioListView.swift
  VoiceRecorder/Presentation/AudioList/AudioListViewController.swift
  VoiceRecorder/Util/Helper/Observable.swift
Labels: Add, Refactor

#16 [#14] 리스트뷰 UI 작업
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder/Presentation/AudioList/AudioListTableViewCell/AudioListTableViewCell.swift
  VoiceRecorder/Presentation/AudioList/AudioListView.swift
  VoiceRecorder/Presentation/AudioList/AudioListViewController.swift
Labels: Style, 승찬

#18 [#17] FirebaseStorage 데이터를 테이블뷰에 로드
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder/Domain/Entity/AudioInformation.swift
  VoiceRecorder/Presentation/AudioList/Cell/AudioListTableViewCell.swift
  VoiceRecorder/Presentation/AudioList/View/AudioListView.swift
  VoiceRecorder/Presentation/AudioList/View/AudioListViewController.swift
  VoiceRecorder/Presentation/AudioList/ViewModel/AudioListViewModel.swift
Labels: Feat, 승찬

#22 [#19] fileURL 접근 방식 및 UI 관련 수정
  VoiceRecorder/Data/Repository/FirebaseRepository.swift
  VoiceRecorder/Presentation/AudioList/Cell/AudioListTableViewCell.swift
  VoiceRecorder/Presentation/Play/View/PlayView.swift
Labels: Fix, 국

#24 [#23] RecordingView UI 및 기능 구현
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder/Application/SceneDelegate.swift
  VoiceRecorder/Data/Repository/FirebaseRepository.swift
  VoiceRecorder/Domain/Inteface/Repository/AudioRepository.swift
  VoiceRecorder/Info.plist
  VoiceRecorder/Presentation/AudioList/View/AudioListViewController.swift
  VoiceRecorder/Presentation/Recording/RecordingView.swift
  VoiceRecorder/Presentation/Recording/RecordingViewController.swift
  VoiceRecorder/Presentation/Recording/VeiwModel/RecordingViewModel.swift
  VoiceRecorder/Presentation/Recording/View/RecordingView.swift
  VoiceRecorder/Presentation/Recording/View/RecordingViewController.swift
  VoiceRecorder/Util/Extension/Alert ++ Extension.swift
  VoiceRecorder/Util/Extension/Date ++ Extension.swift
  VoiceRecorder/Util/Manager/RecordPermissionManager.swift
Labels: Feat, Style, 승찬

#26 [#25] TableView Delete 기능 구현
  VoiceRecorder/Presentation/AudioList/View/AudioListViewController.swift
  VoiceRecorder/Presentation/AudioList/ViewModel/AudioListViewModel.swift
Labels: Feat, 국

#28 [#27] 오디오 파형 구현
  VoiceRecorder.xcodeproj/project.pbxproj
  VoiceRecorder/Domain/Inteface/Repository/PlayViewModel.swift
  VoiceRecorder/Presentation/Play/View/PlayView.swift
  VoiceRecorder/Presentation/Play/View/PlayViewController.swift
  VoiceRecorder/Util/Manager/AudioPlayManager.swift
  VoiceRecorder/Util/Manager/WaveFromGenerator.swift
  VoiceRecorder/Util/Protocol/AudioPlayViewModelable.swift
Labels: Feat, Style, 날라

#30 [#25] PlayViewController title 데이터 생성
  VoiceRecorder/Presentation/Play/View/PlayViewController.swift
Labels: Feat, 국

#31 [#29] PlayView 파형 기준선 구현
  VoiceRecorder.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  VoiceRecorder/Presentation/Play/View/PlayView.swift
  VoiceRecorder/Presentation/Play/View/PlayViewController.swift
Labels: Style, 승찬

#33 [#32] AudioListTableView didSelect 시 배경색 유지
  VoiceRecorder/Presentation/AudioList/View/AudioListViewController.swift
Labels: Fix, 승찬

#35 [#34] 자잘한 버그 수정
  VoiceRecorder/Application/AppDelegate.swift
  VoiceRecorder/Presentation/AudioList/View/AudioListView.swift
  VoiceRecorder/Presentation/AudioList/View/AudioListViewController.swift
  VoiceRecorder/Presentation/AudioList/ViewModel/AudioListViewModel.swift
  VoiceRecorder/Presentation/Play/View/PlayView.swift
  VoiceRecorder/Presentation/Recording/View/RecordingView.swift
  VoiceRecorder/Presentation/Recording/View/RecordingViewController.swift
Labels: Fix, 국
